//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dx29.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedPublicResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedPublicResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dx29.Web.Resources.SharedPublicResource", typeof(SharedPublicResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The {0} must be at least 6 characters long..
        /// </summary>
        public static string The_password_must_have_at_least_6_characters_long {
            get {
                return ResourceManager.GetString("The_password_must_have_at_least_6_characters_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The {0} must have at least one number (0-9)..
        /// </summary>
        public static string The_password_must_have_at_least_one_digit {
            get {
                return ResourceManager.GetString("The_password_must_have_at_least_one_digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The {0} must have at least one lowercase(&apos;a&apos; - &apos;z&apos;) character.&quot;.
        /// </summary>
        public static string The_password_must_have_at_least_one_lower_case_character {
            get {
                return ResourceManager.GetString("The_password_must_have_at_least_one_lower_case_character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The {0} must have at least one non alphanumeric character. (i.e. ! _ *).
        /// </summary>
        public static string The_password_must_have_at_least_one_non_alphanumeric_character {
            get {
                return ResourceManager.GetString("The_password_must_have_at_least_one_non_alphanumeric_character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The {0} must have at least one uppercase(&apos;A&apos; - &apos;Z&apos;) character..
        /// </summary>
        public static string The_password_must_have_at_least_one_upper_case_character {
            get {
                return ResourceManager.GetString("The_password_must_have_at_least_one_upper_case_character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must accept the privacy policy..
        /// </summary>
        public static string You_must_accept_the_privacy_policy {
            get {
                return ResourceManager.GetString("You_must_accept_the_privacy_policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must agree with the data processing by Dx29..
        /// </summary>
        public static string You_must_agree_with_the_data_processing_by_Dx29 {
            get {
                return ResourceManager.GetString("You_must_agree_with_the_data_processing_by_Dx29", resourceCulture);
            }
        }
    }
}
