//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dx29.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UISharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UISharedResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dx29.Data.Resources.UISharedResource", typeof(UISharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The field birthdate is required.
        /// </summary>
        public static string Birthdate_is_required {
            get {
                return ResourceManager.GetString("Birthdate_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The field gender is required.
        /// </summary>
        public static string Gender_is_required {
            get {
                return ResourceManager.GetString("Gender_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid email address.
        /// </summary>
        public static string Invalid_Email_Address {
            get {
                return ResourceManager.GetString("Invalid_Email_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The field name is required.
        /// </summary>
        public static string Name_is_required {
            get {
                return ResourceManager.GetString("Name_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name is too long..
        /// </summary>
        public static string Name_is_too_long {
            get {
                return ResourceManager.GetString("Name_is_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notes must be at max 250 characters long..
        /// </summary>
        public static string Notes_must_be_at_max_250_characters_long {
            get {
                return ResourceManager.GetString("Notes_must_be_at_max_250_characters_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The email address is required.
        /// </summary>
        public static string The_email_address_is_required {
            get {
                return ResourceManager.GetString("The_email_address_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The end date must be after the start date and the date of bith, and before today&apos;s date..
        /// </summary>
        public static string The_end_date_must_be_after_the_start_date_before_todays_date_and_after_birthdate {
            get {
                return ResourceManager.GetString("The_end_date_must_be_after_the_start_date_before_todays_date_and_after_birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The start date cannot be later than today and must be after the date of birth..
        /// </summary>
        public static string The_start_date_cannot_be_later_than_today_and_must_be_after_birthdate {
            get {
                return ResourceManager.GetString("The_start_date_cannot_be_later_than_today_and_must_be_after_birthdate", resourceCulture);
            }
        }
    }
}
